package Presentacion;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        //maximizar el formulario principal
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        dpaneFondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        abrrC = new javax.swing.JMenu();
        sumuregirtrarventa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sumuClientes = new javax.swing.JMenuItem();
        sumuUsuarios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        sumuCategorias = new javax.swing.JMenuItem();
        sumuAgregarProducto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE INFORMACIÓN PARA EL CONTROL DE VENTAS");

        dpaneFondo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dpaneFondoLayout = new javax.swing.GroupLayout(dpaneFondo);
        dpaneFondo.setLayout(dpaneFondoLayout);
        dpaneFondoLayout.setHorizontalGroup(
            dpaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        dpaneFondoLayout.setVerticalGroup(
            dpaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_menu.png"))); // NOI18N
        mnuSalir.setText("ARCHIVO");
        mnuSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Ayuda");
        mnuSalir.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem2);

        jMenuBar1.add(mnuSalir);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-empresa-48.png"))); // NOI18N
        jMenu6.setText("EMPRESA");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem4.setText("Mitsuko");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Proveedores");
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        abrrC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_ventas.png"))); // NOI18N
        abrrC.setText("VENTAS");
        abrrC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        sumuregirtrarventa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sumuregirtrarventa.setText("registrar venta");
        sumuregirtrarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumuregirtrarventaActionPerformed(evt);
            }
        });
        abrrC.add(sumuregirtrarventa);

        jMenuBar1.add(abrrC);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_registrar.png"))); // NOI18N
        jMenu3.setText("REGISTRAR");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        sumuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sumuClientes.setText("Clientes");
        sumuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumuClientesActionPerformed(evt);
            }
        });
        jMenu3.add(sumuClientes);

        sumuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sumuUsuarios.setText("Empleados");
        sumuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumuUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(sumuUsuarios);
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_productos.png"))); // NOI18N
        jMenu1.setText("PRODUCTOS");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        sumuCategorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sumuCategorias.setText("Seguro del Producto");
        sumuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumuCategoriasActionPerformed(evt);
            }
        });
        jMenu1.add(sumuCategorias);

        sumuAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sumuAgregarProducto.setText("Agregar Producto");
        sumuAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumuAgregarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(sumuAgregarProducto);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_reportes.png"))); // NOI18N
        jMenu4.setText("REPORTES");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-inventario-30.png"))); // NOI18N
        jMenu7.setText("INVENTARIO");
        jMenu7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        jMenuItem6.setText("Inventario");
        jMenu7.add(jMenuItem6);

        jMenuItem7.setText("entrada");
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("salida");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpaneFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpaneFondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void sumuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumuClientesActionPerformed
        ifrmClientes fc = new ifrmClientes();
        CentrarVentana(fc);
        
       //dpaneFondo.add(fc);
       //fc.setVisible(true);
    }//GEN-LAST:event_sumuClientesActionPerformed
    public void CentrarVentana (JInternalFrame form){
        
        dpaneFondo.add(form);
        Dimension dim = dpaneFondo.getSize();
        Dimension dfr = form.getSize();
        form.setLocation ((dim.width-dfr.width)/2, (dim.height-dfr.height)/2);
        form.setVisible(true);
    }        
    
    
    
   
    private void sumuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumuUsuariosActionPerformed
        ifrmEmpleado fc = new ifrmEmpleado();
        CentrarVentana(fc);
    }//GEN-LAST:event_sumuUsuariosActionPerformed

    private void sumuregirtrarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumuregirtrarventaActionPerformed
            
    }//GEN-LAST:event_sumuregirtrarventaActionPerformed

    private void sumuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumuCategoriasActionPerformed
       
    }//GEN-LAST:event_sumuCategoriasActionPerformed

    private void sumuAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumuAgregarProductoActionPerformed
        ifrmProductos fp = new ifrmProductos();
        CentrarVentana(fp);
    }//GEN-LAST:event_sumuAgregarProductoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ifrmSalidaMoto fm = new  ifrmSalidaMoto();
        CentrarVentana(fm);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abrrC;
    private javax.swing.JDesktopPane dpaneFondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem sumuAgregarProducto;
    private javax.swing.JMenuItem sumuCategorias;
    private javax.swing.JMenuItem sumuClientes;
    private javax.swing.JMenuItem sumuUsuarios;
    private javax.swing.JMenuItem sumuregirtrarventa;
    // End of variables declaration//GEN-END:variables
}
